# Generated by Django 2.1.2 on 2018-10-06 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ku_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Time_Create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
