# Generated by Django 2.1.2 on 2018-10-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_app', '0002_client_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Phone_Client',
            field=models.CharField(default=123, max_length=9, verbose_name='Телефон клиента'),
            preserve_default=False,
        ),
    ]
